[package]
name = "buffer-graphics-lib"
version = "0.7.1"
edition = "2021"
authors = ["Ray Britton <raybritton@pm.me>"]
description = "Simple graphics library for buffers"
license-file = "LICENSE"
repository = "https://github.com/raybritton/buffer-graphics-lib"
readme = "README.md"
homepage = "https://github.com/raybritton/buffer-graphics-lib"
keywords = ["graphics", "gamedev", "simple"]
categories = ["graphics", "game-development"]

[features]
default = ["image_loading", "serde_derive"]
image_loading = ["image", "serde_json"]
serde_derive = ["serde"]

[dependencies]
thiserror = "1.0"
#graphics-shapes = "0.1.4"
graphics-shapes = {path="../graphics-shapes"}
serde = { version = "1.0", features = ["derive"], optional = true }
image = { version = "0.24.3", optional = true }
serde_json = { version = "1.0", optional = true }

[dev-dependencies]
fastrand = "1.6"
anyhow = "1.0"