[package]
name = "buffer-graphics-lib"
version = "0.12.6"
edition = "2021"
authors = ["Emma Britton <emmabritton@pm.me>"]
description = "Simple graphics library for buffers"
license-file = "LICENSE"
repository = "https://github.com/emmabritton/buffer-graphics-lib"
readme = "README.md"
keywords = ["graphics", "gamedev", "simple"]
categories = ["graphics", "game-development"]

[features]
default = ["serde_derive", "ici"]
image_loading = ["image"]
serde_derive = ["serde"]
ici = ["ici-files"]

[dependencies]
thiserror = "1.0.51"
graphics-shapes = "0.2.6"
serde = { version = "1.0.193", features = ["derive"], optional = true }
image = { version = "0.24.7", optional = true }
log = "0.4.20"
ici-files = { version = "0.1.4", optional = true }
fnv = "1.0.7"

[dev-dependencies]
fastrand = "2.0.1"
anyhow = "1.0.75"