[package]
name = "buffer-graphics-lib"
version = "0.11.1"
edition = "2021"
authors = ["Emma Britton <emmabritton@pm.me>"]
description = "Simple graphics library for buffers"
license-file = "LICENSE"
repository = "https://github.com/emmabritton/buffer-graphics-lib"
readme = "README.md"
keywords = ["graphics", "gamedev", "simple"]
categories = ["graphics", "game-development"]

[features]
default = ["serde_derive", "ici"]
image_loading = ["image"]
serde_derive = ["serde"]
ici = ["ici-files"]

[dependencies]
thiserror = "1.0"
graphics-shapes = "0.2.2"
serde = { version = "1.0", features = ["derive"], optional = true }
image = { version = "0.24.3", optional = true }
log = "0.4.17"
ici-files = { version = "0.1.2", optional = true }

[dev-dependencies]
fastrand = "1.6"
anyhow = "1.0"