[package]
name = "buffer-graphics-lib"
version = "0.15.0"
edition = "2021"
authors = ["Emma Britton <emmabritton@pm.me>"]
description = "Simple graphics library for buffers"
license-file = "LICENSE"
repository = "https://github.com/emmabritton/buffer-graphics-lib"
readme = "README.md"
keywords = ["graphics", "gamedev", "simple"]
categories = ["graphics", "game-development"]

[features]
default = ["serde", "ici"]
image_loading = ["image_lib"]
serde = ["dep:serde", "graphics-shapes/serde"]
ici = ["ici-files"]
mint = ["graphics-shapes/mint"]

[dependencies]
thiserror = "1.0.56"
graphics-shapes = { version = "0.4.0", default-features = false }
serde = { version = "1.0.194", features = ["derive"], optional = true }
image_lib = { package = "image", version = "0.24.7", optional = true }
log = "0.4.20"
ici-files = { version = "0.1.5", optional = true }
fnv = "1.0.7"

[dev-dependencies]
fastrand = "2.0.1"
anyhow = "1.0.79"